### PR TITLE
GPII-2290: Added the logic to include a folder in the Desktop

### PR DESCRIPTION
**Pull request by javihernandez**

### CODE REVIEW

**Comment by javihernandez** [comment]
@minogian and/or @Thanos21 , can you take a look at this pull request?

**Comment by minogian** [comment]
I'm missing the 2 files that are supposed to be in the gpii-hst-tools folder but tested it with dummies and it seems fine to me.

Can you merge or should I tell @Thanos21 to do it?

**Comment by javihernandez** [comment]
@minogian thanks for the quick review!
Sorry, I should've mention that these two files are being pulled during the provisioning stage, see this pull request https://github.com/GPII/gpii-app/pull/9.

**Comment by javihernandez** [comment]
Oh, and btw, it would be great if @Thanos21 can merge it, since I don't want to break our pr-merge normal workflow.

**Pull request merged**
